In [2]:
!pip install numpy

In [3]:
import numpy as np

In [31]:
#create arrays using numpy
#1d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
arr1.reshape(1,5)

[1 2 3 4 5]
(5,)


array([[1, 2, 3, 4, 5]])

In [ ]:
#2 d array -> 2 opening and closing bracets    

arr2 =  np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


create an array with all ones

In [34]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

identity array

In [ ]:
np.eye((3)) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Attributes of Numpy

In [43]:
arr = np.array([[1,2,3],[4,5,6]])

In [47]:
print("array ->", arr)
print("shape->", arr.shape)
print("no. of dimensions->", arr.ndim)
print("size(number of elements->",arr.size)

array -> [[1 2 3]
 [4 5 6]]
shape-> (2, 3)
no. of dimensions-> 2
size(number of elements-> 6


Numpy Vectorised Operatoions: it will happend elementwise. for same indexes.

In [67]:
arr1 = np.array([1,2,3,4,7])
arr2 = np.array([1,2,5,4,1])

In [68]:
#add
print(arr1+arr2)

#sub
print(arr1-arr2)

#mul
print(arr1*arr2)

#div
print(arr1/arr2)

[2 4 8 8 8]
[ 0  0 -2  0  6]
[ 1  4 15 16  7]
[1.  1.  0.6 1.  7. ]


Universal fucntions: applicable to all arrays

In [72]:
arr = np.array([2,3,4,5,6])
#sqrt
print(np.sqrt(arr))

#exponentional
print(np.exp(arr))

#sine
print(np.sin(arr))

#log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


Slicing And Indexing

In [82]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,1],[1,2,4,1,6]])
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 1]
 [1 2 4 1 6]]


In [105]:
#select 1st element
print(arr[0][4])

# print space
print(" ")

#select 9 1 1 6(last sq kinda)
print(arr[1:,3:])

# print space
print(" ")

# pickup 2,3,7,8
print(arr[0:2,1:3])

5
 
[[9 1]
 [1 6]]
 
[[2 3]
 [7 8]]


In [114]:
print(arr)

arr[0,0] = 250

print(arr)

arr[1:]=90
print(arr)

[[250   2   3   4   5]
 [  6   7   8   9   1]
 [  1   2   4   1   6]]
[[250   2   3   4   5]
 [  6   7   8   9   1]
 [  1   2   4   1   6]]
[[250   2   3   4   5]
 [ 90  90  90  90  90]
 [ 90  90  90  90  90]]


Practical Applications

Statistical Concept: Normalisation->
to have a mean of 0 and std dev of 1

In [118]:
#to have a mean of 0 and std dev of 1
data = np.array([1,2,3,4,5])

#calc mean and std dev:
mean = np.mean(data)
std_dev = np.std(data)

#normalise the data:
normalise = (data-mean)/std_dev

print("normalised data: ", normalise)

normalised data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
